//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RE_SHMUP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RE-SHMUP.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Time.
        /// </summary>
        internal static string BestTimeString {
            get {
                return ResourceManager.GetString("BestTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus: Right Trigger or Shift.
        /// </summary>
        internal static string FocusControlsString {
            get {
                return ResourceManager.GetString("FocusControlsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Display.
        /// </summary>
        internal static string FullScreenButton {
            get {
                return ResourceManager.GetString("FullScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice Job! Press (Y)/R!.
        /// </summary>
        internal static string GoodJobString {
            get {
                return ResourceManager.GetString("GoodJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiragana.
        /// </summary>
        internal static string HiraganaTest {
            get {
                return ResourceManager.GetString("HiraganaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string JapaneseLabel {
            get {
                return ResourceManager.GetString("JapaneseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanji.
        /// </summary>
        internal static string KanjiTest {
            get {
                return ResourceManager.GetString("KanjiTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katakana.
        /// </summary>
        internal static string KatakanaTest {
            get {
                return ResourceManager.GetString("KatakanaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Lysithea Unit 1 by blasting meteors!.
        /// </summary>
        internal static string LysitheaPlotString {
            get {
                return ResourceManager.GetString("LysitheaPlotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move: Left Stick or WASD/Arrow Keys.
        /// </summary>
        internal static string MoveControlsString {
            get {
                return ResourceManager.GetString("MoveControlsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit (or ESC).
        /// </summary>
        internal static string QuitButton {
            get {
                return ResourceManager.GetString("QuitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game: (BACK) or ESC.
        /// </summary>
        internal static string QuitControlsString {
            get {
                return ResourceManager.GetString("QuitControlsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset: (Y) or R.
        /// </summary>
        internal static string ResetControlsString {
            get {
                return ResourceManager.GetString("ResetControlsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoot: (A) or Z/Space.
        /// </summary>
        internal static string ShootControlsString {
            get {
                return ResourceManager.GetString("ShootControlsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with (A), Space or Z.
        /// </summary>
        internal static string StartGameString {
            get {
                return ResourceManager.GetString("StartGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Deep of Space.
        /// </summary>
        internal static string TempTitleString {
            get {
                return ResourceManager.GetString("TempTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string TimeString {
            get {
                return ResourceManager.GetString("TimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept missiles!.
        /// </summary>
        internal static string WatchOutString {
            get {
                return ResourceManager.GetString("WatchOutString", resourceCulture);
            }
        }
    }
}
